### ISSUE TITLE
RE: Hello...

### ISSUE THREAD

**Issue by silver2row** [MalavPatel3501/BeagleBone-AI--mpBBAI-IO-Python-Library#1]
Hello,

I am receiving this error while trying to `make` the .dts file under /BeagleBoard-DeviceTrees/src/arm/am5729-beagleboneai-mpcustom.dts

    DTC     src/arm/am5729-beagleboneai-mpcustom.dtb
    Error: src/arm/am5729-beagleboneai-mpcustom.dts:2.1-2 syntax error
    FATAL ERROR: Unable to parse input tree
    make[1]: *** [Makefile:207: src/arm/am5729-beagleboneai-mpcustom.dtb] Error 1
    make: *** [Makefile:171: src/arm/am5729-beagleboneai-mpcustom.dtb] Error 2

Does this error mean anything to you?

Seth

    uname -a: Linux beaglebone 4.14.108-ti-r135
    cat /etc/dogtag: BeagleBoard.org Debian Buster IoT TIDL Image 2020-04-06

**Comment by MalavPatel3501** [comment]
Hello,

Please install first device tree package
Using below command

1) cd  (go to root)
2) git clone https://github.com/beagleboard/BeagleBoard-DeviceTrees -b
v4.14.x-ti

3) cd BeagleBoard-DeviceTrees
4) nano src/arm/am5729-beagleboneai.dts
5) you copy dts file in /src/arm/
6) make /src/arm/am5729-mpcustombeagkeboneai.dtb (.dtb extension dbs name
same
7) make install
6) cp dtb file in /boot/dtbs
7) update uEnv.txt file

**Comment by MalavPatel3501** [comment]
Hello Dear,

it's a line Comment error. i updated this error in file so please download
updated .dts file and make again it's work 100%.

Please let me know if you have any query.

Thanks & Regards,
Malav Patel

**Comment by silver2row** [comment]
Hello...whatever you changed made the compilation work. Thank you. 

Seth

P.S. Now, does the source you made work w/ just importing os from Python3? I am wondering b/c I have a bi-color LED I was going to test out w/ P9_14 and P9_16 and PWM on the BBAI. If you have time, please if you would, clue me in on how to accomplish this task. If not, that is okay too. I will keep trying.
