### ISSUE TITLE
RE: Setting up the .dts and Unknown Behavior

### ISSUE THREAD

**Issue by silver2row** [MalavPatel3501/BeagleBone-AI--mpBBAI-IO-Python-Library#2]
Hello,

I am setting up the .dts file w/ make. That is done. It works. I have found a way to make the LED light up (on/off). Thank you. 

Also, I would like to try to figure out how to make a portion of the .dts file for PWM access on pwmchip0 if possible. 

I will start to research .dts files on elixir.bootlin.com at some point or online via some key search terms.

Seth

P.S. I am reading the TRM now for the am5729. I am skipping around and looking for "clues." Anyway, enjoy and I will wait for a reply in case you find time.

**Comment by MalavPatel3501** [comment]
Dear,

please update below function in "mpBBAIIO.py"  :

def analogRead(self,pin):
        if pin in analogPinDef:
                fileName = "/sys/bus/iio/devices/iio:device0/" +
(analogPinDef [pin])
                fw = open(fileName, "r")
                ADCdata = fw.read()
                fw.close()
                return ADCdata
        else:
                print ("analogRead error: Pin " + channel + " is not
defined as an analog in pin in the pin definit$
                return -1;

Kindly let me know if you need any information.

Thanks,
Malav

**Comment by silver2row** [comment]
Hello Malav,

Seth here. I see the analogRead(self, pin): function is listed for the ADC onboard the AI. How about the pwmchip example. I am not finding the correct file references, i.e. mpBBAI-PWM.py. 

...

    device  export  npwm  power  subsystem  uevent  unexport

...

These are the files I have in /sys/class/pwm/pwmchip0/ only. I do not have the `period `file or any other files I need.

Is this done by default or should the .dts file you and TI.com made work w/ PWM on /sys/class/pwm/pwmchip0/?

Seth
